service: api-programacion
org: danielcaballeros

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::397279833444:role/LabRole
  environment:
    TABLE_NAME_PROGRAMACION: ${sls:stage}-tp_programacion
    LAMBDA_VALIDAR_TOKEN: api-usuarios-${sls:stage}-validar_token

functions:
  crearProgramacion:
    handler: crearProgramacion.handler
    events:
      - http:
          path: /programacion
          method: post
          cors: true

  obtenerProgramacionByPelicula:
    handler: obtenerProgramacionByPelicula.handler
    events:
      - http:
          path: /programacion/{tenant_id}/{ordenamiento}
          method: get
          cors: true

  obtenerProgramaciones:
    handler: obtenerProgramacioneByCine.handler
    events:
      - http:
          path: /programaciones
          method: get
          cors: true


resources:
  Resources:
    ProgramacionTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME_PROGRAMACION}
        AttributeDefinitions:
          - AttributeName: tenantcine_id
            AttributeType: S
          - AttributeName: ordenamiento
            AttributeType: S
          - AttributeName: tenantpelicula_id
            AttributeType: S 
          - AttributeName: ordenamiento_GSI
            AttributeType: S
        KeySchema:
          - AttributeName: tenantcine_id
            KeyType: HASH
          - AttributeName: ordenamiento
            KeyType: RANGE
        # Índice Secundario Global (GSI)
        GlobalSecondaryIndexes:
          - IndexName: PeliculaIndex
            KeySchema:
              - AttributeName: tenantpelicula_id
                KeyType: HASH
              - AttributeName: ordenamiento_GSI
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST